name: Deploy Backend (Render)
on:
  push:
    branches: [ main ]
    paths:
      - "app/**"
      - "requirements.txt"
      - "wsgi.py"
      - "Procfile"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: 'curl -fsS -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"'
